import type { NextPage } from "next";
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHeart } from "@fortawesome/free-solid-svg-icons";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title> Welcome to liblaf.top! </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://liblaf.top"> liblaf.top! </a>
        </h1>

        <p className={styles.description}> Life blooms like a flower </p>

        <div className={styles.grid}>
          <a href="https://blog.liblaf.top" className={styles.card}>
            <h2> Blog &rarr; </h2>
            <p> My blog to record the moments of life. </p>
          </a>

          <a href="https://cdn.liblaf.top" className={styles.card}>
            <h2> Cloud Drive &rarr; </h2>
            <p> An index &amp; manager of Onedrive based on serverless. </p>
          </a>

          <a href="https://wydyf.liblaf.top" className={styles.card}>
            <h2> 未央书院答疑坊 &rarr; </h2>
            <p> 加入我们, 为同学们答疑解惑! </p>
          </a>

          <a href="https://blog.liblaf.top/about/" className={styles.card}>
            <h2> About &rarr; </h2>
            <p> About me. </p>
          </a>
        </div>

        <h2> More to come ... </h2>
      </main>

      <footer className={styles.footer}>
        Made by &nbsp;
        <a href="https://github.com/liblaf"> liblaf </a>
        &nbsp; with &nbsp;
        <i className={styles.heart}>
          <FontAwesomeIcon icon={faHeart} beat />
        </i>
      </footer>
    </div>
  );
};

export default Home;
